# Create a Numpy array filled with all zeros | Python

In [13]:
#We can use Numpy.zeros() method to do this task. This method takes three parameters, discussed below –
#shape : integer or sequence of integers
#order  : C_contiguous or F_contiguous
#         C-contiguous order in memory(last index varies the fastest)
#         C order means that operating row-rise on the array will be slightly quicker
#         FORTRAN-contiguous order in memory (first index varies the fastest).
#         F order means that column-wise operations will be faster. 
#dtype : [optional, float(byDeafult)] Data type of returned array.
import numpy as np
a = np.zeros([3,3], dtype = int) # shape will be passed in list format, will create 2-d of zeros
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [14]:
import numpy as np
a = np.zeros(3, dtype=int)
a
  


array([0, 0, 0])

In [16]:
a = np.zeros([4,4], dtype=float) # we make it float as well
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])