# How to create an empty and a full NumPy array?

In [1]:
#Sometimes there is a need to create an empty and full array simultaneously for a particular question. 
#In this situation, we have two functions named as numpy.empty() and numpy.full() to create an empty and full arrays.
#syntax
#numpy.full(shape, fill_value, dtype = None, order = ‘C’)
#numpy.empty(shape, dtype = float, order = ‘C’) 
import numpy as np

In [2]:
emp = np.empty((3,4), dtype=int)
print(emp)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [3]:
empa = np.empty((3, 4), dtype=int)
print("Empty Array")
print(empa)

Empty Array
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [4]:
emp = np.full((3,4), 22, dtype=int)

In [5]:
emp

array([[22, 22, 22, 22],
       [22, 22, 22, 22],
       [22, 22, 22, 22]])

In [6]:
emp = np.full((3,4), 22, dtype=float)
emp

array([[22., 22., 22., 22.],
       [22., 22., 22., 22.],
       [22., 22., 22., 22.]])